### PR TITLE
Base skeleton for TheHostingTool

### PR DESCRIPTION
**Pull request by xaoseric**
This is the base skeleton that will be used for TheHostingTool.

### CODE REVIEW

**Comment by xaoseric** [comment]
sill waiting on @kmark

**Comment by kmark** [comment]
Thanks for the PR! Can you explain to me a little more about the structure of the project? The "core" included by this will be the actual, I'm assuming Laravel-powered, THT2?

**Comment by xaoseric** [comment]
This PR is the skeleton that will bootstrap the core package, and yes, the core package is powered by Laravel. It is designed to be secure, and provide easy customization as well as modification. For the most part, the current database structure will work, hoping to have backwards compatibility to make it easier for those that want to upgrade their current installations.

**Comment by kmark** [comment]
Sounds good. I wouldn't worry too much at all about backwards compatibility with the old database. That ideally should be redesigned as well. I would think it'd be worth it to break backwards compatibility and just make an upgrade script.

**Pull request merged**
